# Generated by Django 4.2.7 on 2023-12-17 05:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('labels', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='labels',
            field=models.ManyToManyField(blank=True, help_text='Select one or more tags.', to='labels.labelmodel',
                                         verbose_name='Labels'),
        ),
    ]
